Repository TEAM-OMG-iOS/TravelTale, pull requests merged in 2024-06, with the labels that each got.

#4 [Fix] gray5, gray10, gray20 수정
  TravelTale/Common/Extensions/UIColor+Extension.swift
  TravelTale/Info.plist
Labels: enhancement

#18 [Feat] 나의 여행 탭
  TravelTale.xcodeproj/project.pbxproj
  TravelTale.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TravelTale/Common/Class/Observable.swift
  TravelTale/Common/Views/Reusables/LightGreenButton.swift
  TravelTale/Common/Views/Reusables/TravelTableViewCell.swift
  TravelTale/Views/Travels/Travel/SpaceFooterView.swift
  TravelTale/Views/Travels/Travel/TravelMemoryView.swift
  TravelTale/Views/Travels/Travel/TravelPlanView.swift
  TravelTale/Views/Travels/Travel/TravelSectionHeaderView.swift
  TravelTale/Views/Travels/Travel/TravelView.swift
  TravelTale/Views/Travels/TravelMemoryViewController.swift
  TravelTale/Views/Travels/TravelPlanViewController.swift
  TravelTale/Views/Travels/TravelSegment.swift
  TravelTale/Views/Travels/TravelViewController.swift
  TravelTale/Views/Travels/TravelViewModel.swift
Labels: feat

#28 Feature/26 discovery region setting
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Common/Extensions/UIColor+Extension.swift
  TravelTale/Views/Discoveries/Discovery/DiscoveryCell.swift
  TravelTale/Views/Discoveries/Discovery/DiscoveryRegionView.swift
  TravelTale/Views/Discoveries/Discovery/DiscoveryView.swift
  TravelTale/Views/Discoveries/DiscoveryRegionViewController.swift
  TravelTale/Views/Discoveries/DiscoveryViewController.swift
  TravelTale/Views/TabBar/TabBarViewController.swift
Labels: feat

#24 [Feat] 메모 추가 페이지 구현
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Common/Views/Reusables/DaySelectPopover.swift
  TravelTale/Common/Views/Reusables/TimeSelectPopover.swift
  TravelTale/Views/Common/AddSchedule/ScheduleCreateView.swift
  TravelTale/Views/Common/AddSchedule/ScheduleCreateViewController.swift
  TravelTale/Views/Common/AddSchedule/TravelSelectView.swift
  TravelTale/Views/Common/AddSchedule/TravelSelectViewController.swift
  TravelTale/Views/Travels/MemoAdd/MemoAddView.swift
  TravelTale/Views/Travels/MemoAddViewController.swift
  TravelTale/Views/Travels/PlaceAddEdit/PlaceAddEditView.storyboard
  TravelTale/Views/Travels/PlaceAddViewController.swift
Labels: feat

#33 Feature/2 add to mytravel + IQKeyboardManagerSwift 추가
  TravelTale.xcodeproj/project.pbxproj
  TravelTale.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TravelTale/AppDelegate.swift
  TravelTale/Common/Views/Reusables/DaySelectPopover.swift
  TravelTale/Common/Views/Reusables/DaySelectPopoverView.swift
  TravelTale/Common/Views/Reusables/DaySelectPopoverViewController.swift
  TravelTale/Common/Views/Reusables/TimeSelectPopover.swift
  TravelTale/Common/Views/Reusables/TimeSelectPopoverView.swift
  TravelTale/Common/Views/Reusables/TimeSelectPopoverViewController.swift
  TravelTale/Views/Common/AddSchedule/ScheduleCreateView.swift
  TravelTale/Views/Common/AddSchedule/ScheduleCreateViewController.swift
  TravelTale/Views/Common/AddSchedule/TravelSelectView.swift
  TravelTale/Views/Common/AddSchedule/TravelSelectViewController.swift
  TravelTale/Views/Travels/MemoAdd/MemoAddView.swift
  TravelTale/Views/Travels/MemoAddViewController.swift
  TravelTale/Views/Travels/PlaceAddEdit/PlaceAddEditView.storyboard
Labels: feat

#34 Feature/32 discovery region modal
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Common/RegionData.swift
  TravelTale/Views/Discoveries/Discovery/DiscoveryRegionView.swift
  TravelTale/Views/Discoveries/Discovery/DiscoveryView.swift
  TravelTale/Views/Discoveries/DiscoveryRegionModal/DiscoveryRegionModalViewController.swift
  TravelTale/Views/Discoveries/DiscoveryRegionViewController.swift
  TravelTale/Views/Discoveries/DiscoveryViewController.swift
Labels: feat

#39 Feature/35 my page view
  TravelTale.xcodeproj/project.pbxproj
  TravelTale.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TravelTale/Assets.xcassets/mypage/Contents.json
  TravelTale/Assets.xcassets/mypage/accommodation_circle.imageset/Contents.json
  TravelTale/Assets.xcassets/mypage/accommodation_circle.imageset/accommodation_circle.svg
  TravelTale/Assets.xcassets/mypage/entertainment_circle.imageset/Contents.json
  TravelTale/Assets.xcassets/mypage/entertainment_circle.imageset/entertainment_circle.svg
  TravelTale/Assets.xcassets/mypage/restaurant_circle.imageset/Contents.json
  TravelTale/Assets.xcassets/mypage/restaurant_circle.imageset/restaurant_circle.svg
  TravelTale/Assets.xcassets/mypage/tourist_spot_circle.imageset/Contents.json
  TravelTale/Assets.xcassets/mypage/tourist_spot_circle.imageset/tourist_spot_circle.svg
  TravelTale/Common/Views/Reusables/BookMarkButton.swift
  TravelTale/Views/Discoveries/Discovery/DiscoveryView.swift
  TravelTale/Views/Discoveries/DiscoveryRegionViewController.swift
  TravelTale/Views/MyPages/MyPage/MyPageView.swift
  TravelTale/Views/MyPages/MyPageViewController.swift
Labels: feat

#38 Feature/14 place add edit UI
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Common/Views/Reusables/DaySelectPopoverViewController.swift
  TravelTale/Views/Travels/PlaceAddEdit/PlaceAddEditView.storyboard
  TravelTale/Views/Travels/PlaceAddViewController.swift
  TravelTale/Views/Travels/PlaceAdditionViewController.swift
  TravelTale/Views/Travels/PlaceEditionViewController.swift
Labels: feat

#50 Feature/49 tabBar
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Common/Extensions/CALayer+Extension.swift
  TravelTale/Views/TabBar/TabBarViewController.swift
Labels: feat

#47 Feature/46 my page table view
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Common/Views/Reusables/BookMarkButton.swift
  TravelTale/Views/Common/Category/CategoryTableViewCell.swift
  TravelTale/Views/Common/Category/CategoryView.swift
  TravelTale/Views/Discoveries/Discovery/DiscoveryCell.swift
  TravelTale/Views/Discoveries/DiscoveryCategory/AccommodationViewController.swift
  TravelTale/Views/Discoveries/DiscoveryCategory/DiscoveryCategoryViewController.swift
  TravelTale/Views/Discoveries/DiscoveryCategory/EntertainmentViewController.swift
  TravelTale/Views/Discoveries/DiscoveryCategory/RestaurantViewController.swift
  TravelTale/Views/Discoveries/DiscoveryCategory/TouristSpotViewController.swift
  TravelTale/Views/Discoveries/DiscoveryViewController.swift
  TravelTale/Views/MyPages/BookMark/BookMarkAccommodationViewController.swift
  TravelTale/Views/MyPages/BookMark/BookMarkEntertainmentViewController.swift
  TravelTale/Views/MyPages/BookMark/BookMarkRestaurantViewController.swift
  TravelTale/Views/MyPages/BookMark/BookMarkTotalViewController.swift
  TravelTale/Views/MyPages/BookMark/BookMarkTouristSpotViewController.swift
  TravelTale/Views/MyPages/BookMark/BookMarkViewController.swift
  TravelTale/Views/MyPages/MyPage/MyPageServiceTableViewCell.swift
  TravelTale/Views/MyPages/MyPage/MyPageView.swift
  TravelTale/Views/MyPages/MyPageViewController.swift
Labels: feat

#42 Feature/22 calendar view
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Views/Common/Location/LocationTableViewCell.swift
  TravelTale/Views/Travels/TravelAddCalendar/Calendar/CalendarBaseView.swift
  TravelTale/Views/Travels/TravelAddCalendar/Calendar/CalendarDayRangeIndicatorView.swift
  TravelTale/Views/Travels/TravelAddCalendar/Calendar/CalendarDayView.swift
  TravelTale/Views/Travels/TravelAddCalendar/Calendar/CalendarMonthDayView.swift
  TravelTale/Views/Travels/TravelAddCalendar/Calendar/CalendarMonthView.swift
  TravelTale/Views/Travels/TravelAddCalendar/TravelAddCalendarView.swift
  TravelTale/Views/Travels/TravelAddCalendar/TravelAddCalendarViewController.swift
  TravelTale/Views/Travels/TravelAddCalender/TravelAddCalenderView.swift
  TravelTale/Views/Travels/TravelAddCalender/TravelAddCalenderViewController.swift
  TravelTale/Views/Travels/TravelAddPlace/TravelAddPlaceModalViewController.swift
  TravelTale/Views/Travels/TravelAddPlace/TravelAddPlaceView.swift
  TravelTale/Views/Travels/TravelAddPlace/TravelAddPlaceViewController.swift
  TravelTale/Views/Travels/TravelAddTitle/TravelAddTitleView.swift
  TravelTale/Views/Travels/TravelAddTitle/TravelAddTitleViewController.swift
  TravelTale/Views/Travels/TravelReschedule/TravelRenewCalendarView.swift
  TravelTale/Views/Travels/TravelReschedule/TravelRenewCalendarViewController.swift
  TravelTale/Views/Travels/TravelReschedule/TravelRescheduleView.swift
  TravelTale/Views/Travels/TravelReschedule/TravelRescheduleViewController.swift
  TravelTale/Views/Travels/TravelUpdate/TravelUpdateCalendarView.swift
  TravelTale/Views/Travels/TravelUpdate/TravelUpdateCalendarViewController.swift
  TravelTale/Views/Travels/TravelUpdate/TravelUpdateView.swift
  TravelTale/Views/Travels/TravelUpdate/TravelUpdateViewController.swift
Labels: feat

#52 [Feature] #51 - splash 이미지 설정
  TravelTale/Assets.xcassets/splash/splash-scale.imageset/Contents.json
  TravelTale/Assets.xcassets/splash/splash-scale.imageset/splash-1.png
  TravelTale/Assets.xcassets/splash/splash-scale.imageset/splash-2.png
  TravelTale/Assets.xcassets/splash/splash-scale.imageset/splash-3.png
  TravelTale/Assets.xcassets/splash/splash.imageset/Contents.json
  TravelTale/Assets.xcassets/splash/splash.imageset/splash.svg
  TravelTale/Base.lproj/LaunchScreen.storyboard
Labels: feat

#54 Feature/53 travel-cell 이미지 hidden 함수 생성
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Common/Extensions/String+Extension.swift
  TravelTale/Common/Views/Reusables/TravelTableViewCell.swift
  TravelTale/Views/Common/AddSchedule/TravelSelectViewController.swift
  TravelTale/Views/Travels/Travel/TravelMemoryView.swift
  TravelTale/Views/Travels/Travel/TravelPlanView.swift
  TravelTale/Views/Travels/Travel/TravelSectionHeaderView.swift
  TravelTale/Views/Travels/Travel/TravelView.swift
  TravelTale/Views/Travels/TravelMemoryViewController.swift
  TravelTale/Views/Travels/TravelPlanViewController.swift
  TravelTale/Views/Travels/TravelSegment.swift
  TravelTale/Views/Travels/TravelViewController.swift
  TravelTale/Views/Travels/TravelViewModel.swift
Labels: enhancement

#63 Feature/21 memory
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Common/Views/Reusables/TravelTableViewCell.swift
  TravelTale/Views/Common/AddSchedule/TravelSelectViewController.swift
  TravelTale/Views/Travels/Travel/TravelMemoryView.swift
  TravelTale/Views/Travels/Travel/TravelPlanView.swift
  TravelTale/Views/Travels/TravelAddTitle/TravelAddTitleViewController.swift
  TravelTale/Views/Travels/TravelMemory/TravelMemoryAddView.swift
  TravelTale/Views/Travels/TravelMemory/TravelMemoryAddViewController.swift
  TravelTale/Views/Travels/TravelMemory/TravelMemoryDetailEditView.swift
  TravelTale/Views/Travels/TravelMemory/TravelMemoryDetailEditViewController.swift
  TravelTale/Views/Travels/TravelMemory/TravelMemoryDetailHeaderView.swift
  TravelTale/Views/Travels/TravelMemory/TravelMemoryDetailTableViewCell.swift
  TravelTale/Views/Travels/TravelMemory/TravelMemoryDetailView.swift
  TravelTale/Views/Travels/TravelMemory/TravelMemoryDetailViewController.swift
  TravelTale/Views/Travels/TravelMemory/TravelMemoryEditPhotoCollectionViewCell.swift
  TravelTale/Views/Travels/TravelMemoryViewController.swift
  TravelTale/Views/Travels/TravelPlanViewController.swift
  TravelTale/Views/Travels/TravelViewController.swift
Labels: feat

#65 Feature/62 my page notice tableview
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Assets.xcassets/detail/Contents.json
  TravelTale/Assets.xcassets/detail/annotation.imageset/Contents.json
  TravelTale/Assets.xcassets/detail/annotation.imageset/notification.svg
  TravelTale/Common/Views/Reusables/CustomPopUpView.swift
  TravelTale/Common/Views/Reusables/GrayBackgroundView.swift
  TravelTale/Common/Views/Reusables/GrayButton.swift
  TravelTale/Common/Views/Reusables/GreenButton.swift
  TravelTale/Common/Views/Reusables/PlaceDetailView.swift
  TravelTale/OpenSourceLicense.rtf
  TravelTale/TermPrivacyPolicy.rtf
  TravelTale/Views/Common/Place/PhoneOptionsAlert/PhoneOptionsAlertView.swift
  TravelTale/Views/Common/Place/PhoneOptionsAlert/PhoneOptionsAlertViewController.swift
  TravelTale/Views/Common/Place/PlaceDetailImageCollectionViewCell.swift
  TravelTale/Views/Common/Place/PlaceDetailView.swift
  TravelTale/Views/Common/Place/PlaceDetailViewController.swift
  TravelTale/Views/Discoveries/DiscoveryCategory/AccommodationViewController.swift
  TravelTale/Views/Discoveries/DiscoveryCategory/DiscoveryCategoryViewController.swift
  TravelTale/Views/Discoveries/DiscoveryCategory/EntertainmentViewController.swift
  TravelTale/Views/Discoveries/DiscoveryCategory/RestaurantViewController.swift
  TravelTale/Views/Discoveries/DiscoveryCategory/TouristSpotViewController.swift
  TravelTale/Views/Discoveries/DiscoveryViewController.swift
  TravelTale/Views/MyPages/BookMark/BookMarkAccommodationViewController.swift
  TravelTale/Views/MyPages/BookMark/BookMarkEntertainmentViewController.swift
  TravelTale/Views/MyPages/BookMark/BookMarkRestaurantViewController.swift
  TravelTale/Views/MyPages/BookMark/BookMarkTotalViewController.swift
  TravelTale/Views/MyPages/BookMark/BookMarkTouristSpotViewController.swift
  TravelTale/Views/MyPages/BookMark/BookMarkViewController.swift
  TravelTale/Views/MyPages/MyPage/MyPageServiceTableViewCell.swift
  TravelTale/Views/MyPages/MyPage/MyPageView.swift
  TravelTale/Views/MyPages/MyPageViewController.swift
  TravelTale/Views/MyPages/Terms/TermOpenSourceViewController.swift
  TravelTale/Views/MyPages/Terms/TermPrivacyPolicyViewController.swift
  TravelTale/Views/MyPages/Terms/TermView.swift
  TravelTale/Views/Travels/MemoAddViewController.swift
  TravelTale/Views/Travels/TravelAddCalendar/Calendar/CalendarBaseView.swift
  TravelTale/Views/Travels/TravelAddCalendar/Calendar/CalendarDayRangeIndicatorView.swift
  TravelTale/Views/Travels/TravelAddCalendar/Calendar/CalendarDayView.swift
  TravelTale/Views/Travels/TravelAddCalendar/Calendar/CalendarMonthDayView.swift
  TravelTale/Views/Travels/TravelAddCalendar/Calendar/CalendarMonthView.swift
  TravelTale/Views/Travels/TravelAddCalendar/TravelAddCalendarView.swift
  TravelTale/Views/Travels/TravelAddCalendar/TravelAddCalendarViewController.swift
  TravelTale/Views/Travels/TravelUpdate/TravelUpdateCalendarView.swift
  TravelTale/Views/Travels/TravelUpdate/TravelUpdateCalendarViewController.swift
  TravelTale/Views/Travels/TravelUpdate/TravelUpdateView.swift
  TravelTale/Views/Travels/TravelViewController.swift
Labels: feat

#71 Feature/67 discovery region data
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Presentation/Common/CategoryTab/View/CategoryTabTableViewCell.swift
  TravelTale/Presentation/Common/CategoryTab/View/CategoryTabView.swift
  TravelTale/Presentation/Common/PlaceDetails/PlaceDetail/View/PlaceDetailCollectionViewCell.swift
  TravelTale/Presentation/Common/PlaceDetails/PlaceDetail/View/PlaceDetailViewController.swift
  TravelTale/Presentation/Common/PlaceDetails/PlaceDetailAlert/View/PlaceDetailAlertView.swift
  TravelTale/Presentation/Common/PlaceDetails/PlaceDetailAlert/View/PlaceDetailAlertViewController.swift
  TravelTale/Presentation/Common/PlaceDetails/PlaceDetailToast/View/PlaceDetailToastView.swift
  TravelTale/Presentation/Common/Region/View/RegionTableViewCell.swift
  TravelTale/Presentation/Common/Region/View/RegionView.swift
  TravelTale/Presentation/Discoveries/Discovery/View/DiscoveryView.swift
  TravelTale/Presentation/Discoveries/Discovery/View/DiscoveryViewController.swift
  TravelTale/Presentation/Discoveries/DiscoveryCategories/DiscoveryCategory/View/DiscoveryCategoryViewController.swift
  TravelTale/Presentation/Discoveries/DiscoveryCategories/DiscoveryCategoryTab/View/DiscoveryCategoryTabAccommodationViewController.swift
  TravelTale/Presentation/Discoveries/DiscoveryCategories/DiscoveryCategoryTab/View/DiscoveryCategoryTabEntertainmentViewController.swift
  TravelTale/Presentation/Discoveries/DiscoveryCategories/DiscoveryCategoryTab/View/DiscoveryCategoryTabRestaurantViewController.swift
  TravelTale/Presentation/Discoveries/DiscoveryCategories/DiscoveryCategoryTab/View/DiscoveryCategoryTabTouristSpotViewController.swift
  TravelTale/Presentation/Discoveries/DiscoveryRegion/View/DiscoveryRegionView.swift
  TravelTale/Presentation/Discoveries/DiscoveryRegion/View/DiscoveryRegionViewController.swift
  TravelTale/Presentation/Discoveries/DiscoveryRegionModal/View/DiscoveryRegionModalSidoViewController.swift
  TravelTale/Presentation/Discoveries/DiscoveryRegionModal/View/DiscoveryRegionModalSigunguViewController.swift
  TravelTale/Presentation/Discoveries/DiscoveryRegionModal/View/DiscoveryRegionModalViewController.swift
  TravelTale/Presentation/MyPages/MyPage/View/Component/MyPageBookMarkButton.swift
  TravelTale/Presentation/MyPages/MyPage/View/MyPageTableViewCell.swift
  TravelTale/Presentation/MyPages/MyPage/View/MyPageView.swift
  TravelTale/Presentation/MyPages/MyPage/View/MyPageViewController.swift
  TravelTale/Presentation/MyPages/MyPageCategories/MyPageCategory/View/MyPageCategoryViewController.swift
  TravelTale/Presentation/MyPages/MyPageCategories/MyPageCategoryTab/View/MyPageCategoryTabAccommodationViewController.swift
  TravelTale/Presentation/MyPages/MyPageCategories/MyPageCategoryTab/View/MyPageCategoryTabEntertainmentViewController.swift
  TravelTale/Presentation/MyPages/MyPageCategories/MyPageCategoryTab/View/MyPageCategoryTabRestaurantViewController.swift
  TravelTale/Presentation/MyPages/MyPageCategories/MyPageCategoryTab/View/MyPageCategoryTabTotalViewController.swift
  TravelTale/Presentation/MyPages/MyPageCategories/MyPageCategoryTab/View/MyPageCategoryTabTouristSpotViewController.swift
  TravelTale/Presentation/MyPages/MyPageTerm/View/MyPageTermOpenSourceViewController.swift
  TravelTale/Presentation/MyPages/MyPageTerm/View/MyPageTermPrivacyPolicyViewController.swift
  TravelTale/Presentation/MyPages/MyPageTerm/View/MyPageTermView.swift
  TravelTale/Presentation/Travels/Plans/PlanAdds/PlanAddSidos/PlanAddSidoModal/View/TravelAddPlaceModalViewController.swift
Labels: feat

#72 Feature/66 bind-plan-memory
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Presentation/Travels/MemoryAddEditPhotoCollectionViewCell.swift
  TravelTale/Presentation/Travels/MemoryAddEditView.swift
  TravelTale/Presentation/Travels/MemoryAddEditViewController.swift
  TravelTale/Presentation/Travels/MemoryDetailTableHeaderView.swift
  TravelTale/Presentation/Travels/MemoryDetailTableViewCell.swift
  TravelTale/Presentation/Travels/MemoryDetailView.swift
  TravelTale/Presentation/Travels/MemoryDetailViewController.swift
  TravelTale/Presentation/Travels/MemorySelectView.swift
  TravelTale/Presentation/Travels/MemorySelectViewController.swift
  TravelTale/Presentation/Travels/MemoryView.swift
  TravelTale/Presentation/Travels/MemoryViewController.swift
  TravelTale/Presentation/Travels/Plans/Plan/View/PlanTableFooterView.swift
  TravelTale/Presentation/Travels/Plans/Plan/View/PlanTableHeaderView.swift
  TravelTale/Presentation/Travels/Plans/Plan/View/PlanView.swift
  TravelTale/Presentation/Travels/Plans/Plan/View/PlanViewController.swift
  TravelTale/Presentation/Travels/Travel/View/TravelViewController.swift
  TravelTale/Presentation/Travels/TravelMemoryDetailEditViewController.swift
  TravelTale/Presentation/Utils/Views/Reusables/Cell/TravelTableViewCell.swift
Labels: enhancement, feat

#82 Design/81 bgcolor
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Presentation/Travels/MemoryAddEditView.swift
  TravelTale/Presentation/Travels/MemoryDetailView.swift
  TravelTale/Presentation/Travels/MemorySelectView.swift
  TravelTale/Presentation/Travels/MemoryView.swift
  TravelTale/Presentation/Travels/Plans/Plan/View/PlanView.swift
Labels: enhancement

#78 [Fix] MemoryAddEditView 오류 수정
  TravelTale/Presentation/Travels/MemoryAddEditView.swift
  TravelTale/Presentation/Travels/MemoryAddEditViewController.swift
  TravelTale/Presentation/Travels/MemoryDetailView.swift
Labels: enhancement

#91 Feature/90 tabbar(그림자, 반투명 제거), splash(에셋변경)
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Presentation/TabBar/View/TabBarViewController.swift
  TravelTale/Presentation/Travels/MemoryAddEditPhotoCollectionViewCell.swift
  TravelTale/Presentation/Travels/MemoryDetailTableViewCell.swift
  TravelTale/Presentation/Travels/MemoryDetailViewController.swift
  TravelTale/Presentation/Travels/MemorySelectView.swift
  TravelTale/Presentation/Utils/Extensions/CALayer+Extension.swift
  TravelTale/Presentation/Utils/Views/Reusables/Cell/TravelTableViewCell.swift
  TravelTale/Resources/Assets.xcassets/splash/splash-scale.imageset/splash-1.png
  TravelTale/Resources/Assets.xcassets/splash/splash-scale.imageset/splash-2.png
  TravelTale/Resources/Assets.xcassets/splash/splash-scale.imageset/splash-3.png
Labels: enhancement

#95 Feature/94 travel empty view
  TravelTale.xcodeproj/project.pbxproj
  TravelTale/Presentation/Travels/MemorySelectView.swift
  TravelTale/Presentation/Travels/MemorySelectViewController.swift
  TravelTale/Presentation/Travels/MemoryView.swift
  TravelTale/Presentation/Travels/MemoryViewController.swift
  TravelTale/Presentation/Travels/Plans/Plan/View/PlanView.swift
  TravelTale/Presentation/Travels/Plans/Plan/View/PlanViewController.swift
  TravelTale/Presentation/Utils/Views/Reusables/Cell/TravelTableViewCell.swift
  TravelTale/Presentation/Utils/Views/Reusables/View/NotFoundView.swift
  TravelTale/Resources/Assets.xcassets/splash/splash_scale.imageset/Contents.json
  TravelTale/Resources/Assets.xcassets/splash/splash_scale.imageset/splash-1.png
  TravelTale/Resources/Assets.xcassets/splash/splash_scale.imageset/splash-2.png
  TravelTale/Resources/Assets.xcassets/splash/splash_scale.imageset/splash-3.png
  TravelTale/Resources/Assets.xcassets/travel/not_found_train.imageset/Contents.json
  TravelTale/Resources/Assets.xcassets/travel/not_found_train.imageset/not_found_train.svg
  TravelTale/Resources/Base.lproj/LaunchScreen.storyboard
Labels: feat

#98 [Design] #97 - (TabBarViewController) translucent 오류 appearance로 해결
  TravelTale/Presentation/TabBar/View/TabBarViewController.swift
Labels: bug

#103 [Add] #100 - app icon 등록
  TravelTale/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  TravelTale/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  TravelTale/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  TravelTale/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  TravelTale/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  TravelTale/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  TravelTale/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  TravelTale/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  TravelTale/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  TravelTale/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  TravelTale/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  TravelTale/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: feat

#102 Feature/101 not found train 에셋 수정
  TravelTale/Presentation/Utils/Views/Reusables/View/NotFoundView.swift
  TravelTale/Resources/Assets.xcassets/travel/not_found_train.imageset/not_found_train.svg
Labels: enhancement

#107 [Refactor] #106 - fetchNoMemoryTravels()를 Manager로 대체
  TravelTale/Presentation/Travels/MemorySelectViewController.swift
Labels: feat
