Repository TEAM-OMG-iOS/TravelTale, pull requests merged in 2024-07, with the labels that each got.

#111 Feature/110 not found api view
  TravelTale/Presentation/Common/CategoryTab/View/CategoryTabTableViewCell.swift
  TravelTale/Presentation/Common/CategoryTab/View/CategoryTabView.swift
  TravelTale/Presentation/Discoveries/DiscoveryCategories/DiscoveryCategoryTab/View/DiscoveryCategoryTabAccommodationViewController.swift
  TravelTale/Presentation/Discoveries/DiscoveryCategories/DiscoveryCategoryTab/View/DiscoveryCategoryTabEntertainmentViewController.swift
  TravelTale/Presentation/Discoveries/DiscoveryCategories/DiscoveryCategoryTab/View/DiscoveryCategoryTabRestaurantViewController.swift
  TravelTale/Presentation/Discoveries/DiscoveryCategories/DiscoveryCategoryTab/View/DiscoveryCategoryTabTouristSpotViewController.swift
  TravelTale/Presentation/MyPages/MyPage/View/MyPageTableViewCell.swift
  TravelTale/Presentation/MyPages/MyPageCategories/MyPageCategoryTab/View/MyPageCategoryTabAccommodationViewController.swift
  TravelTale/Presentation/MyPages/MyPageCategories/MyPageCategoryTab/View/MyPageCategoryTabEntertainmentViewController.swift
  TravelTale/Presentation/MyPages/MyPageCategories/MyPageCategoryTab/View/MyPageCategoryTabRestaurantViewController.swift
  TravelTale/Presentation/MyPages/MyPageCategories/MyPageCategoryTab/View/MyPageCategoryTabTotalViewController.swift
  TravelTale/Presentation/MyPages/MyPageCategories/MyPageCategoryTab/View/MyPageCategoryTabTouristSpotViewController.swift
Labels: feat

#115 [Feat] #114 - (TravelTableViewCell) 지역 label 앞 2글자만 바인딩
  TravelTale/Presentation/Utils/Views/Reusables/Cell/TravelTableViewCell.swift
Labels: enhancement

#122 schedule 생성 시 년,월,일이 오늘날짜로 저장되던 문제 수정
  TravelTale/Presentation/Common/DetailSchedule/DetailScheduleAdd/View/DetailScheduleAddViewController.swift
Labels: bug

#131 Feature/127 memory 수정 시 확인버튼 오류 수정
  TravelTale/Presentation/Travels/MemoryAddEditView.swift
  TravelTale/Presentation/Travels/MemoryAddEditViewController.swift
Labels: bug

#130 [Feat] #125 (Info) 라이트 모드 고정 추가
  TravelTale/Resources/Info.plist
Labels: bug, feat

#132 [Fix] #129 - (DiscoveryView) 카테고리 버튼 오토레이아웃 수정
  TravelTale/Presentation/Discoveries/Discovery/View/DiscoveryView.swift
Labels: bug
